spring:
  application:
    name: task-management

  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mysql
    password: mysql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  sql:
    init:
      mode: always

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

jwt:
  access:
    token:
      expiration: 60000000
  refresh:
    token:
      expiration: 60000000000